name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: bolt-cli-linux
          - os: macOS-latest
            output-name: bolt-cli-mac
          - os: windows-latest
            output-name: bolt-cli-windows.exe

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - run: mkdir build

      - name: Code Generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build CLI
        run: dart compile exe cli/main.dart -v -o build/${{ matrix.output-name }} --define=AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output-name }}
          path: build/${{ matrix.output-name }}
          retention-days: 14
